- title: GPG Key
  label: C7A0 5E3F C972 098C
  icon: fa-key
  link: /keys/gpg.txt

- title: Twitter
  label: '@markadams'
  icon: fa-twitter
  link: https://twitter.com/markadams

- title: Bitbucket
  label: markadams
  icon: fa-bitbucket
  link: https://bitbucket.org/markadams

- title: Github
  label: mark-adams
  icon: fa-github
  link: https://github.com/mark-adams

- title: LinkedIn
  label: markladams
  icon: fa-linkedin
  link: https://www.linkedin.com/in/markladams

- title: Keybase
  label: kramsmada
  icon: fa-lock
  link: https://keybase.io/kramsmada
